version: '3.8'

services:
  app:
    image: jonnywf/minimundo:latest
    container_name: mini-mundo-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=miniMundo
      - DB_USERNAME=root
      - DB_PASSWORD=1234cinco

  db:
    image: mysql:8.0
    container_name: miniMundo
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: miniMundo
      MYSQL_ROOT_PASSWORD: 1234cinco
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
